name       : haskell-hs-bibutils
version    : 6.8.0.0
release    : 3
source     :
    - https://hackage.haskell.org/package/hs-bibutils-6.8.0.0/hs-bibutils-6.8.0.0.tar.gz : 4cab7f3866df0fe58c6eefa3ce5207ce2c2fd6b8e763f54cd952553c0281d06b
license    : GPL-2.0-or-later
component  : programming.haskell
summary    : Haskell bindings to Chris Putnam's bibutils, a library that interconverts between various bibliography formats using a common MODS-format XML intermediate.
description: |
    Haskell bindings to Chris Putnam's bibutils, a library that interconverts between various bibliography formats using a common MODS-format XML intermediate.
builddeps  :
    - haskell-cabal-install
    - haskell-syb-devel
rundeps    :
    - devel:
        - haskell-syb-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
