name       : haskell-hs-bibutils
version    : 5.5
release    : 1
source     :
    - https://hackage.haskell.org/package/hs-bibutils-5.5/hs-bibutils-5.5.tar.gz : 95f9f34be9f3145da8acc8a0e9de379236cfe31c5a9bc0eb9489e77402a4c55d
license    : GPL-2.0
component  : programming.haskell
summary    : Haskell bindings to Chris Putnam's bibutils, a library that interconverts between various bibliography formats using a common MODS-format XML intermediate.
description: |
    Haskell bindings to Chris Putnam's bibutils, a library that interconverts between various bibliography formats using a common MODS-format XML intermediate.
builddeps  :
    - haskell-cabal-install
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
