name       : haskell-hs-bibutils
version    : 6.2.0.1
release    : 2
source     :
    - https://hackage.haskell.org/package/hs-bibutils-6.2.0.1/hs-bibutils-6.2.0.1.tar.gz : 4b668090049bf67f107b8bcd39a4664c00b78ff596de9ccb63720af49ed4a630
license    : GPL-2.0
component  : programming.haskell
summary    : Haskell bindings to Chris Putnam's bibutils, a library that interconverts between various bibliography formats using a common MODS-format XML intermediate.
description: |
    Haskell bindings to Chris Putnam's bibutils, a library that interconverts between various bibliography formats using a common MODS-format XML intermediate.
builddeps  :
    - haskell-cabal-install
    - haskell-syb
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
